export type WriterInput = { topic: string };
export type WriterOutput = { title: string; html: string };

export async function generateDraft({ topic }: WriterInput): Promise<WriterOutput> {
  const safe = topic.trim().replace(/\s+/g, ' ');
  const title = safe.replace(/\b\w/g, (c) => c.toUpperCase());
  const html = `<h1>${title}</h1>
<p>This short draft was generated by the local stub writer. Replace this with your gateway later.</p>
<ul>
  <li>Key idea #1 about "${safe}"</li>
  <li>Key idea #2</li>
  <li>Call to action</li>
</ul>`;
  return { title, html };
}

